### PR TITLE
chore: Adding purchase domain icon to setup screen card

### PR DESCRIPTION
**Pull request by aykanburcak**

### CODE REVIEW

**Review by lukefrogger — APPROVED** [review]
The updated Icon component in the Setup Card Task makes images with lots of padding really small. It would probably be best to remove as much padding as possible, but not a requirement.

**Comment by aykanburcak** [comment]
@lukefrogger Thanks for the reminder. I think we're not gonna be using those icons in the V2 setup cards but if we decide to use those again we need to revise all of them to remove the padding inside of the image itself.

**Comment by bswatson** [comment]
Is this a change for v1, v2, or both?

**Comment by aykanburcak** [comment]
@bswatson It's a change for only V1.

**Review by chumpgrub — APPROVED** [review]

**Pull request merged**
