### PR TITLE
Jump nav component and story

### PR DESCRIPTION
**Pull request by aykanburcak**
### Jira Ticket
[SITE-119](https://moderntribe.atlassian.net/browse/SITE-119)
This PR adds the Jump Nav component and its corresponding story into the WME Framework.

### Screenshot
Screenshot on 2022-11-22 at 15-44-33

### CODE REVIEW

**Review by lukefrogger — APPROVED** [review]
LGTM

**Review by chumpgrub — CHANGES_REQUESTED** [review]
Nice work, Aykan! 

As I as reviewing the Story, I changed a `remainingTask` property to `0` and the presentation [didn't seem right](https://d.pr/9UeVuI). I don't think there's ever a use-case for displaying `0`, either by itself or in the `TaskNumber` component, so I think we should prevent these situations by updating the check on line 65 of `jump-nav.tsx`.

**Comment by aykanburcak** [comment]
Great catch @chumpgrub!
I have updated it.

**Review by chumpgrub — APPROVED** [review]
Noice! Approved!

**Pull request merged**
