### PR TITLE
Splitting go live wizard into 2 wizards

### PR DESCRIPTION
**Pull request by aykanburcak**

### CODE REVIEW

**Comment by chumpgrub** [comment]
I still have to complete the code review, but I'm liking where this is going. Thank you for catching all the typos and making the naming consistent throughout.

I came across one thing on my local environment while testing this branch, and wanted to surface it before I finish reviewing. For some reason the "Continue" button on the `DomainConnectWizard` is continues to be disabled, even [after a successful verification](http://p.tri.be/i/IGYgy7).

**Comment by aykanburcak** [comment]
@chumpgrub Looks like it's because of the changed total step numbers.
I have changed the step numbers according to the latest structure.
Everything seems working properly now!
http://p.tri.be/v/rKd62e

**Review by chumpgrub — APPROVED** [review]
This does the trick! Thank you

**Comment by bswatson** [comment]
@aykanburcak @chumpgrub Should be good to go!

**Pull request merged**
