### PR TITLE
Site Details screen

### PR DESCRIPTION
**Pull request by aykanburcak**
## Description
- Adds site details screen as a separate package
- Adds site visibility and Google Analytics setup cards to site details screen

## Screenshot
Screen Capture on 2022-12-16 at 19-13-17

### CODE REVIEW

**Comment by aykanburcak** [comment]
Thanks @lukefrogger 
I just thought why not return both label and chip color in the getPasswordStrength util function so made an update on that 😬

**Review by lukefrogger — APPROVED** [review]
🚀

**Review by chumpgrub — APPROVED** [review]
Really nice work, Aykan!

**Comment by bswatson** [comment]
Updated the base branch to now merge to `main` based on the recent branch updates.

**Pull request merged**
