### PR TITLE
Telemetry Started/Completed

### PR DESCRIPTION
**Pull request by ColtenVanTussenbrook**
### Description
-https://moderntribe.atlassian.net/browse/SITE-35

- Makes AJAX request when a wizard is started
- Makes AJAX request when PayPal or Stripe are completed (the rest are completed by the backend)

Note: my local wanted me to install the webpack-cli, but I can remove that from this PR if needed. It's just a dev dependency though, so I figure it may be needed by other devs as well.

### CODE REVIEW

**Review by chumpgrub — APPROVED** [review]
Ya man! Thanks for this!

**Comment by bswatson** [comment]
Reminder to run `npx changeset` for this PR so the CHANGELOG can automatically get updated and packages deployed when this makes it to `main`.

**Comment by ColtenVanTussenbrook** [comment]
@bswatson did I do that changeset right? This is the first I've heard about doing this, so please let me know if I need to do it another way.

**Comment by bswatson** [comment]
@ColtenVanTussenbrook Yep, that looks good!

**Pull request merged**
